configpath: ~/.config/nom/config.yml
version: ""
feeds:
  - url: https://www.royalroad.com/fiction/syndication/37155
    name: Knight and Smith
  - url: https://www.royalroad.com/fiction/syndication/82152
    name: SbMG
  - url: https://www.royalroad.com/fiction/syndication/39408
    name: Beware of Chicken
  - url: https://www.royalroad.com/fiction/syndication/76478
    name: Hoard
  - url: https://www.royalroad.com/fiction/syndication/92080
    name: Amelia Thornheart
  - url: https://www.royalroad.com/fiction/syndication/62152
    name: Ghost in the City
  - url: https://www.royalroad.com/fiction/syndication/80787
    name: Nova Wars
database: nom.db
ordering: desc
openers:
  - regex: "royalroad"
    cmd: "/d/.config/scripts/nom_open_rr %s"
    takeover: true
filtering:
  defaultIncludeFeedName: false
theme:
  glamour: dark
  titleColor: "62"
  titleColorFg: "231"
  filterColor: "62"
  selectedItemColor: "170"
  readIcon: ✓
http:
  mintls: TLS 1.2
